### ISSUE TITLE
Support more button labels for on-screen keyboards

### ISSUE THREAD

**Issue by snomos** [divvun/kbdgen#13]
There are more buttons with text labels than we have used so far. The following is a number of strings needing support in `kbdgen`, at least so that kbdgen won't stop because of them (some of them are already supported, but included for completeness):

```yaml
keyNames:
  space: gaska
  return: "linnjá\u00ADmolsun" # or use ⏎ for some or all variants, both default and below
  return-alts:
    search: your-word-for-search  # when pressing the return key triggers a search
    go: your-word-for-go-or-open  # when pressing the return key goes to or opens a URL
    send: your-word-for-send      # when pressing the return key sends e.g. an instant message
    join: your-word-for-join      # when pressing the return key joins a wifi net or similar
    cancel: your-word-for-cancel  # when pressing the return key cancels an action
    continue: your-word-for-cont  # when pressing the return key continues a process
    done: your-word-for-done      # when pressing the return key finishes a process
    emergency: word-for-emergency-call # when pressing the return key triggers an emergency call
    next: word-for-next           # when pressing the return key takes you to the next field or similar
    route: word-for-route         # when pressing the return key finds a route or some direction to go
  undo: your-word-for-undo # or a symbol
  redo: your-word-for-redo # or a symbol
```

See e.g. https://developer.apple.com/documentation/uikit/uireturnkeytype/ and similar for other OS's.

The present setup is just:

```yaml
keyNames:
  space: gaska
  return: "linnjá\u00ADmolsun"
```

When support for these strings is added to `kbdgen`, the layout files must be updated accordingly.
